apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: train-ticket-reservation 
  template:
    metadata:
      labels:
        app: train-ticket-reservation
    spec:
      containers:
        - name: myapp
          image: 733544353237.dkr.ecr.us-west-1.amazonaws.com/gowtham7842:1780057717
          ports:
            - containerPort: 8080
